/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colorobserver;

import java.awt.Color;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sistemas
 */
public class ventanaColor extends javax.swing.JFrame implements Observer{
    private ClaseObserver observador;
    /**
     * Creates new form ventanaColor
     */
    public ventanaColor() {
        initComponents();
    }
    
    public ventanaColor(ClaseObserver observador)
    {
        initComponents();
        this.observador=observador;
        setTitle("Usuario 3");
        setLocationRelativeTo(null);
        setLocation(this.getX()+this.getWidth(), this.getY());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        radAmarillo = new javax.swing.JRadioButton();
        radAzul = new javax.swing.JRadioButton();
        radBlanco = new javax.swing.JRadioButton();
        radNegro = new javax.swing.JRadioButton();
        radRojo = new javax.swing.JRadioButton();
        lblColor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione un color");

        buttonGroup1.add(radAmarillo);
        radAmarillo.setText("Amarillo");
        radAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAmarilloActionPerformed(evt);
            }
        });

        buttonGroup1.add(radAzul);
        radAzul.setText("Azul");
        radAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAzulActionPerformed(evt);
            }
        });

        buttonGroup1.add(radBlanco);
        radBlanco.setText("Blanco");
        radBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBlancoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radNegro);
        radNegro.setText("Negro");
        radNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNegroActionPerformed(evt);
            }
        });

        buttonGroup1.add(radRojo);
        radRojo.setText("Rojo");
        radRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radRojoActionPerformed(evt);
            }
        });

        lblColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblColor.setOpaque(true);

        jLabel3.setText("Color Seleccionado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(radBlanco)
                            .addComponent(radNegro)
                            .addComponent(radRojo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radAmarillo)
                                .addGap(36, 195, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radAzul)
                                        .addGap(0, 195, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3)))
                                .addGap(18, 18, 18)))
                        .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(radAmarillo)
                        .addGap(18, 18, 18)
                        .addComponent(radAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(radBlanco)
                .addGap(18, 18, 18)
                .addComponent(radNegro)
                .addGap(18, 18, 18)
                .addComponent(radRojo)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAmarilloActionPerformed
        // TODO add your handling code here:
        if(radAmarillo.isSelected())
        {
            observador.setColor(Color.yellow);
        }
    }//GEN-LAST:event_radAmarilloActionPerformed

    private void radBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBlancoActionPerformed
        // TODO add your handling code here:
        if(radBlanco.isSelected())
        {
            observador.setColor(Color.white);
        }
    }//GEN-LAST:event_radBlancoActionPerformed

    private void radNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNegroActionPerformed
        // TODO add your handling code here:
        if(radNegro.isSelected())
        {
            observador.setColor(Color.black);
        }
        
    }//GEN-LAST:event_radNegroActionPerformed

    private void radAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAzulActionPerformed
        // TODO add your handling code here:
        if(radAzul.isSelected())
        {
            observador.setColor(Color.blue);
        }
    }//GEN-LAST:event_radAzulActionPerformed

    private void radRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radRojoActionPerformed
        // TODO add your handling code here:
        if(radRojo.isSelected())
        {
            observador.setColor(Color.red);
        }
    }//GEN-LAST:event_radRojoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaColor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblColor;
    private javax.swing.JRadioButton radAmarillo;
    private javax.swing.JRadioButton radAzul;
    private javax.swing.JRadioButton radBlanco;
    private javax.swing.JRadioButton radNegro;
    private javax.swing.JRadioButton radRojo;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void update(Observable o, Object arg) 
    {
        
        lblColor.setBackground(observador.getColor());
        switch(observador.getColores().indexOf(observador.getColor()))
        {
            case 0:radAmarillo.setSelected(true);break;
            case 1:radAzul.setSelected(true);break;
            case 2:radBlanco.setSelected(true);break;
            case 3:radNegro.setSelected(true);break;
            case 4:radRojo.setSelected(true);break;   
        }
    }

    /**
     * @return the observador
     */
    

    
}
